const {chromium}=require('/home/user/Tempered/svelte-commerce/node_modules/@playwright/test');
const {snap,OUT}=require('./lib.cjs');
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'});
const ctx=await b.newContext({viewport:{width:1280,height:900},storageState:OUT+'/state.json'});const pg=await ctx.newPage();const log=[];
pg.on('pageerror',e=>log.push('pageerror: '+e.message.slice(0,200)));pg.on('console',m=>{if(m.type()==='error')log.push('console: '+m.text().slice(0,200))});
pg.on('response',async r=>{if(r.url().includes('3001/shop-api')){try{const q=r.request().postData()||'';const t=await r.text();log.push('shop-api '+(q.match(/mutation\s*\w*\s*[({][^{]*\{\s*(\w+)/)?.[1]||q.match(/mutation\s*(\w+)/)?.[1]||'query')+' → '+(/errorCode|"errors"/.test(t)?t.slice(0,300):'ok'))}catch{}}});
await pg.goto('http://localhost:3000/checkout/payment',{waitUntil:'networkidle'});await pg.waitForTimeout(1000);
const radios=await pg.locator('input[name=paymentMethod]').count();console.log('payment radios',radios);
await pg.locator('label:has-text("COD"), text=COD').first().click().catch(e=>console.log('cod click',e.message.slice(0,80)));
await pg.locator('text=STANDARD SHIPPING').first().click().catch(()=>{});
await pg.getByTestId('checkout-button').click();await pg.waitForTimeout(3000);
console.log('URL after review:',pg.url());console.log((await snap(pg,'07-review')).join('\n'));
console.log((await pg.locator('#main').last().innerText()).replace(/\n+/g,' | ').slice(0,900));
await ctx.storageState({path:OUT+'/state.json'});
console.log('--- log');console.log([...new Set(log)].filter(l=>!/CERT_AUTH|TUNNEL|Stripe|ipify/.test(l)).join('\n'));await b.close()})();
